#!/usr/bin/env bash

version=9.2.0854
revision=1

tarball_url="https://github.com/vim/vim/archive/refs/tags/v${version}.tar.gz"
tarball_sha256="b0e3afbc106a0aff2f945e60bf305dc249170cd13ef4d3c5c6cbd34760585c12"

cross_compile=yes

deps="mlibc ncurses"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	cp -a "${source_dir}/." .
	autotools_configure_script="${PWD}/configure"

	autotools_configure \
		--disable-acl \
		--disable-canberra \
		--disable-channel \
		--disable-gpm \
		--disable-gui \
		--disable-libsodium \
		--disable-nls \
		--disable-selinux \
		--with-features=tiny \
		--with-tlib=ncursesw \
		--without-x
}

build() {
	autotools_build
}

package() {
	autotools_install
}
