#!/usr/bin/env bash

version=1.2.0
revision=1

tarball_url="https://libbsd.freedesktop.org/releases/libmd-${version}.tar.xz"
tarball_sha256="ac15ffb8430502fbaccdec66c5a82ee0eab0b0f36220df56710feadfeb13d0a0"

cross_compile=yes

deps="mlibc"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
