#!/usr/bin/env bash

version=1.6.58
revision=5

tarball_url="https://download.sourceforge.net/libpng/libpng-${version}.tar.xz"
tarball_sha256="28eb403f51f0f7405249132cecfe82ea5c0ef97f1b32c5a65828814ae0d34775"

cross_compile=yes

deps="mlibc zlib"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
