[workspace]
resolver = "3"
members = ["xtask", "kernel/arch", "kernel/block", "kernel/boot", "kernel/cpu", "kernel/devfs", "kernel/elf", "kernel/ext4", "kernel/fb-types", "kernel/fbdev", "kernel/fbterm", "kernel/fd", "kernel/futex", "kernel/input", "kernel/interrupt", "kernel/key-decoder", "kernel/line-discipline", "kernel/main", "kernel/memory", "kernel/poll", "kernel/pipe", "kernel/process", "kernel/ps2", "kernel/serial", "kernel/signal", "kernel/syscall", "kernel/terminal", "kernel/test", "kernel/thread", "kernel/time", "kernel/timer-wait", "kernel/tty", "kernel/tty-types", "kernel/utils", "kernel/vfs", "kernel/vm"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
anyhow = "1"
acpi = { version = "5", default-features = false }
bitflags = "2"
buddy_system_allocator = { version = "0.13", default-features = false, features = ["alloc"] }
clap = { version = "4", features = ["derive"] }
embedded-bitmap-fonts = { version = "0.1", default-features = false, features = ["terminus"] }
embedded-graphics = "0.8"
ext4plus = { version = "0.1.0-rc.2", default-features = false, features = ["multi-threaded", "sync"] }
heapless = "0.9"
hashbrown = "0.16"
limine = "0.6"
linkme = "0.3"
object = { version = "0.39", default-features = false, features = ["elf", "read_core"] }
pc-keyboard = "0.9"
qemu-exit = "4"
spin = { version = "0.12", default-features = false, features = ["mutex", "once", "spin_mutex"] }
strum = { version = "0.28", default-features = false, features = ["derive"] }
tap = "1"
uart_16550 = "0.6"
vte = { version = "0.15", default-features = false }
x86_64 = { version = "0.15", features = ["abi_x86_interrupt"] }
x2apic = "0.5"
xshell = "0.2"

roxy-arch.path = "kernel/arch"
roxy-block.path = "kernel/block"
roxy-boot.path = "kernel/boot"
roxy-cpu.path = "kernel/cpu"
roxy-devfs.path = "kernel/devfs"
roxy-elf.path = "kernel/elf"
roxy-ext4.path = "kernel/ext4"
roxy-fb-types.path = "kernel/fb-types"
roxy-fbdev.path = "kernel/fbdev"
roxy-fbterm.path = "kernel/fbterm"
roxy-fd.path = "kernel/fd"
roxy-futex.path = "kernel/futex"
roxy-input.path = "kernel/input"
roxy-interrupt.path = "kernel/interrupt"
roxy-key-decoder.path = "kernel/key-decoder"
roxy-line-discipline.path = "kernel/line-discipline"
roxy-memory.path = "kernel/memory"
roxy-poll.path = "kernel/poll"
roxy-pipe.path = "kernel/pipe"
roxy-process.path = "kernel/process"
roxy-ps2.path = "kernel/ps2"
roxy-serial.path = "kernel/serial"
roxy-signal.path = "kernel/signal"
roxy-syscall.path = "kernel/syscall"
roxy-terminal.path = "kernel/terminal"
roxy-test.path = "kernel/test"
roxy-thread.path = "kernel/thread"
roxy-time.path = "kernel/time"
roxy-timer-wait.path = "kernel/timer-wait"
roxy-tty.path = "kernel/tty"
roxy-tty-types.path = "kernel/tty-types"
roxy-unix-socket.path = "kernel/unix-socket"
roxy-utils.path = "kernel/utils"
roxy-vfs.path = "kernel/vfs"
roxy-vm.path = "kernel/vm"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing_panics_doc = "allow"
pedantic = { level = "warn", priority = -1 }
