[workspace]
resolver = "3"
members = ["xtask", "kernel/arch", "kernel/boot", "kernel/core", "kernel/cpu", "kernel/elf", "kernel/fd", "kernel/futex", "kernel/memory", "kernel/process", "kernel/syscall", "kernel/test", "kernel/thread", "kernel/time", "kernel/utils", "kernel/vm"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
anyhow = "1"
bitflags = "2"
buddy_system_allocator = { version = "0.13", default-features = false, features = ["alloc"] }
clap = { version = "4", features = ["derive"] }
heapless = "0.9"
limine = "0.6"
linkme = "0.3"
object = { version = "0.39", default-features = false, features = ["elf", "read_core"] }
qemu-exit = "4"
spin = { version = "0.12", default-features = false, features = ["mutex", "once", "spin_mutex"] }
tap = "1"
uart_16550 = "0.6"
x86_64 = { version = "0.15", features = ["abi_x86_interrupt"] }
x2apic = "0.5"
xshell = "0.2"

roxy-arch.path = "kernel/arch"
roxy-boot.path = "kernel/boot"
roxy-cpu.path = "kernel/cpu"
roxy-elf.path = "kernel/elf"
roxy-fd.path = "kernel/fd"
roxy-futex.path = "kernel/futex"
roxy-memory.path = "kernel/memory"
roxy-process.path = "kernel/process"
roxy-syscall.path = "kernel/syscall"
roxy-test.path = "kernel/test"
roxy-thread.path = "kernel/thread"
roxy-time.path = "kernel/time"
roxy-utils.path = "kernel/utils"
roxy-vm.path = "kernel/vm"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
