#!/usr/bin/env bash

version=0.0.0.20260728
revision=1

git_url="https://github.com/RoxyOS/mlibc"
commit="de4f85109e7f41668efc9c28cb4a284f99de6f8c"
shallow=no

source_hostdeps="meson"
source_imagedeps="ca-certificates git python3"
source_allow_network=yes

cross_compile=yes
clean_workdirs=no

hostdeps="meson roxy-llvm"
imagedeps="ninja-build pkg-config python3"

source "${base_dir}/build-systems/meson.sh"

prepare() {
	meson subprojects download \
		freestnd-c-hdrs \
		freestnd-cxx-hdrs \
		frigg \
		libsmarter
}

configure() {
	meson_configure \
		-Dcpp_args=-D_GNU_SOURCE \
		-Ddefault_library=both \
		-Dlibgcc_dependency=true \
		-Duse_freestnd_hdrs=enabled
}

build() {
	meson_build
}

package() {
	meson_install
}
