#!/usr/bin/env bash

version=1.0.16
revision=1

tarball_url="https://www.x.org/releases/individual/lib/libXaw-${version}.tar.xz"
tarball_sha256="731d572b54c708f81e197a6afa8016918e2e06dfd3025e066ca642a5b8c39c8f"

cross_compile=yes

# Xaw6 requires only x11/xext/xt/xmu (all present). Xaw7 additionally needs
# libxpm, which is not packaged; disable it to keep the dependency closure small.
deps="mlibc libx11 libxt libxext libxmu xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure \
		--disable-xaw7
}

build() {
	autotools_build
}

package() {
	autotools_install
}
