#!/usr/bin/env bash

version=5.5.0
revision=1

tarball_url="https://www.lua.org/ftp/lua-${version}.tar.gz"
tarball_sha256="57ccc32bbbd005cab75bcc52444052535af691789dba2b9016d5c50640d68b3d"

cross_compile=yes

deps="mlibc"
hostdeps="roxy-llvm"
imagedeps="make"

configure() {
	cp -a "${source_dir}/." .
}

lua_make() {
	make -C "${PWD}" \
		CC="clang --target=x86_64-unknown-roxy --sysroot=/sysroot -std=gnu99" \
		AR="llvm-ar rcu" \
		RANLIB=llvm-ranlib \
		"$@"
}

build() {
	lua_make -j "${parallelism}" posix
}

package() {
	lua_make INSTALL_TOP="${dest_dir}${prefix}" install
}
