#!/usr/bin/env bash

version=5.3
revision=1

tarball_url="https://ftpmirror.gnu.org/gnu/bash/bash-${version}.tar.gz"
tarball_sha256="0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba"

cross_compile=yes

deps="mlibc"
imagedeps="clang compiler-rt lld llvm make"

source "${base_dir}/build-systems/autotools.sh"

configure() {
	autotools_configure \
		--disable-nls \
		--disable-readline \
		--without-bash-malloc
}

build() {
	autotools_build
}

package() {
	autotools_install
}
