#!/usr/bin/env bash

major=5.3
patches=15
version=${major}.${patches}
revision=6

tarball_url="https://ftpmirror.gnu.org/gnu/bash/bash-${major}.tar.gz"
tarball_sha256="0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba"

cross_compile=yes

deps="mlibc"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure \
		--disable-nls \
		--without-bash-malloc \
		CPPFLAGS="-DNEED_EXTERN_PC"
}

build() {
	autotools_build
}

package() {
	autotools_install
}
