#!/usr/bin/env bash

version=1.8.13
revision=1

tarball_url="https://www.x.org/releases/individual/lib/libX11-${version}.tar.xz"
tarball_sha256="69606f485c2c07c14ef64f75b7bb326d48587af33795d9ab3e607c0b5f94f11c"

cross_compile=yes

deps="mlibc xorgproto xtrans libxcb pthread-stubs"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
