#!/usr/bin/env bash

version=2.1.0
revision=3

tarball_url="https://www.x.org/releases/individual/driver/xf86-input-keyboard-${version}.tar.xz"
tarball_sha256="77ce50f28c30347c6eb59169c12c19b639d73f10e49284b2849f023c6dee7c57"

cross_compile=yes

deps="mlibc xorg-server xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
