[package]
name = "roxy-kernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
kernel = []
kernel-test = [
    "dep:linkme",
    "dep:qemu-exit",
    "dep:roxy-test",
    "roxy-test/kernel-test",
    "roxy-arch/kernel-test",
    "roxy-boot/kernel-test",
    "roxy-cpu/kernel-test",
    "roxy-elf/kernel-test",
    "roxy-futex/kernel-test",
    "roxy-memory/kernel-test",
    "roxy-process/kernel-test",
    "roxy-syscall/kernel-test",
    "roxy-thread/kernel-test",
    "roxy-vm/kernel-test",
]

[[bin]]
name = "roxy-kernel"
path = "src/main.rs"
test = false
bench = false
required-features = ["kernel"]

[dependencies]
linkme = { workspace = true, optional = true }
qemu-exit = { workspace = true, optional = true }
spin.workspace = true
uart_16550.workspace = true

roxy-arch.workspace = true
roxy-boot.workspace = true
roxy-cpu.workspace = true
roxy-elf.workspace = true
roxy-futex.workspace = true
roxy-memory.workspace = true
roxy-process.workspace = true
roxy-syscall.workspace = true
roxy-test = { workspace = true, optional = true }
roxy-thread.workspace = true
roxy-time.workspace = true
roxy-utils.workspace = true
roxy-vm.workspace = true

[lints]
workspace = true
