[package]
name = "roxy-memory"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
kernel-test = [
    "dep:linkme",
    "dep:roxy-test",
    "roxy-arch/kernel-test",
    "roxy-boot/kernel-test",
]

[dependencies]
bitflags.workspace = true
buddy_system_allocator.workspace = true
linkme = { workspace = true, optional = true }
spin.workspace = true
x86_64.workspace = true

roxy-arch.workspace = true
roxy-boot.workspace = true
roxy-test = { workspace = true, optional = true }
roxy-utils.workspace = true

[lints]
workspace = true
