#!/usr/bin/env bash

version=0.3.0
revision=1

git_url="https://github.com/RoxyOS/xf86-video-roxyfb"
commit="9571655f9652dfac2363ca8453982418e16034b0"
shallow=no

cross_compile=yes

deps="mlibc xorg-server xorgproto"
hostdeps="roxy-llvm"
imagedeps="meson ninja-build pkg-config"

source "${base_dir}/build-systems/meson.sh"

configure() {
	meson_configure
}

build() {
	meson_build
}

package() {
	meson_install
}
