#!/usr/bin/env bash

version=0.3.1
revision=5

git_url="https://github.com/RoxyOS/xf86-video-roxyfb"
commit="8ea003d4bdc096c17b642342b8eb6a6aceda664c"
shallow=no

cross_compile=yes

deps="mlibc xorg-server xorgproto"
hostdeps="roxy-llvm"
imagedeps="meson ninja-build pkg-config"

source "${base_dir}/build-systems/meson.sh"

configure() {
	meson_configure
}

build() {
	meson_build
}

package() {
	meson_install
}
