#!/usr/bin/env bash

version=1.17.0
revision=1

tarball_url="https://www.x.org/releases/individual/xcb/xcb-proto-${version}.tar.xz"
tarball_sha256="2c1bacd2110f4799f74de6ebb714b94cf6f80fb112316b1219480fd22562148c"

cross_compile=yes

deps="mlibc"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config python3"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
