#!/usr/bin/env bash

version=1.3.7
revision=1

tarball_url="https://www.x.org/releases/individual/lib/libXext-${version}.tar.xz"
tarball_sha256="6c643c7035cdacf67afd68f25d01b90ef889d546c9fcd7c0adf7c2cf91e3a32d"

cross_compile=yes

deps="mlibc libx11 xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
