#!/usr/bin/env bash

version=1.9.4
revision=12

tarball_url="https://www.x.org/releases/individual/driver/xf86-input-mouse-${version}.tar.xz"
tarball_sha256="7f6f8551fc238abdddcf9f38906564c1f8c7dacb0ad947cfc110487aefbd8d4c"

cross_compile=yes

deps="mlibc xorg-server xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	# Roxy's X server configuration (xorg.conf, which includes the optional
	# psaux mouse device as a commented-out block) is bundled by the base
	# metapackage, not here.
	autotools_install
}
