#!/usr/bin/env bash

version=1.3.1
revision=1

tarball_url="https://www.x.org/releases/individual/app/xeyes-${version}.tar.xz"
tarball_sha256="5608d76b7b1aac5ed7f22f1b6b5ad74ef98c8693220f32b4b87dccee4a956eaa"

cross_compile=yes

deps="mlibc libxi libx11 libxt libxext libxmu xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure \
		--without-xrender \
		--without-present
}

build() {
	autotools_build
}

package() {
	autotools_install
}
