[package]
name = "roxy-terminal"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
kernel-test = ["dep:linkme", "dep:roxy-test"]

[dependencies]
linkme = { workspace = true, optional = true }

roxy-fd.workspace = true
roxy-test = { workspace = true, optional = true }

[lints]
workspace = true
