#!/usr/bin/env bash

version=1.4.2
revision=3

tarball_url="https://www.x.org/releases/individual/app/xinit-${version}.tar.xz"
tarball_sha256="b7d8dc8d22ef9f15985a10b606ee4f2aad6828befa437359934647e88d331f23"

cross_compile=yes

deps="mlibc libx11 xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install

	# Use custom xinitrc
	install -D -m 755 "${base_dir}/recipes/xinit/xinitrc" \
		"${dest_dir}/root/.xinitrc"
}
