#!/usr/bin/env bash

version=1.17.0
revision=1

tarball_url="https://www.x.org/releases/individual/xcb/libxcb-${version}.tar.xz"
tarball_sha256="599ebf9996710fea71622e6e184f3a8ad5b43d0e5fa8c4e407123c88a59a6d55"

cross_compile=yes

deps="mlibc xcb-proto libxau pthread-stubs"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config python3"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
