#!/usr/bin/env bash

version=1.1.3
revision=1

tarball_url="https://www.x.org/releases/individual/font/font-misc-misc-${version}.tar.xz"
tarball_sha256="79abe361f58bb21ade9f565898e486300ce1cc621d5285bec26e14b6a8618fed"

cross_compile=yes

deps="mlibc font-util"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config xfonts-utils"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure \
		--with-fontrootdir=/usr/share/fonts/X11 \
		--disable-all-encodings \
		--enable-iso8859-1
}

build() {
	autotools_build
}

package() {
	autotools_install
}
