#!/usr/bin/env bash

version=1.3.2
revision=1

tarball_url="https://zlib.net/zlib-${version}.tar.gz"
tarball_sha256="bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16"

cross_compile=yes

deps="mlibc"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make"

# zlib uses its own configure script, not autoconf, and builds in-tree.
configure() {
	cp -a "${source_dir}/." .

	export CC="clang --target=x86_64-unknown-roxy --sysroot=/sysroot"
	export AR=llvm-ar
	export RANLIB=llvm-ranlib

	./configure --prefix="${prefix}" --shared
}

build() {
	make -j "${parallelism}"
}

package() {
	make DESTDIR="${dest_dir}" install
}
