#!/usr/bin/env bash

version=1.3.1
revision=1

tarball_url="https://www.x.org/releases/individual/lib/libXmu-${version}.tar.xz"
tarball_sha256="81a99e94c4501e81c427cbaa4a11748b584933e94b7a156830c3621256857bc4"

cross_compile=yes

deps="mlibc libx11 libxt libxext xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
