#!/usr/bin/env bash

version=1.8.3
revision=1

tarball_url="https://www.x.org/releases/individual/lib/libXi-${version}.tar.xz"
tarball_sha256="7ad60056f01af4f786cfe93b3a7707447711626fc8da2637bec71a90409babe5"

cross_compile=yes

deps="mlibc libx11 libxext libxfixes xorgproto"
hostdeps="roxy-llvm"
imagedeps="gcc libc6-dev make pkg-config"

source "${base_dir}/build-systems/autotools.sh"

prepare() {
	autotools_patch_roxy_target
}

configure() {
	autotools_configure
}

build() {
	autotools_build
}

package() {
	autotools_install
}
