#!/usr/bin/env bash

version=1
revision=1

# This base metapackage contains the essential software for a normal system.
deps="lua python duktape bash busybox vim evtest xorg-server xf86-video-fbdev xf86-input-mouse twm xeyes xinit"
