Section "ServerFlags"
    Option "AutoAddDevices" "off"
    Option "AutoEnableDevices" "off"
EndSection

Section "Module"
    Load "fbdev"
EndSection

Section "Device"
    Identifier "Card0"
    Driver "roxyfb"
    Option "Device" "/dev/framebuffer"
EndSection

Section "Monitor"
    Identifier "Monitor0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Card0"
    Monitor "Monitor0"
    DefaultDepth 24
EndSection

Section "ServerLayout"
    Identifier "Default Layout"
    Screen 0 "Screen0"
    InputDevice "Keyboard0" "CoreKeyboard"
    InputDevice "Mouse0" "CorePointer"
EndSection

Section "InputDevice"
    Identifier "Keyboard0"
    Driver "keyboard"
    Option "Device" "/dev/keyboard"
EndSection

Section "InputDevice"
    Identifier "Mouse0"
    Driver "mouse"
    Option "Protocol" "Roxy"
    Option "Device" "/dev/mouse"
EndSection