#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

target=x86_64-unknown-none-elf
link=yes
executable=yes
runtime=yes

for argument in "$@"; do
	case "${argument}" in
	-c | -E | -M | -MM | -S | -fsyntax-only)
		link=no
		;;
	-shared)
		executable=no
	;;
	-r)
		executable=no
		runtime=no
		;;
	esac
done

arguments=(
	"--target=${target}"
	--sysroot=/sysroot
	-fno-pic
	-fno-pie
	-fno-stack-protector
)

libraries=()

if [[ ${link} == yes ]]; then
	arguments+=(
		-fuse-ld=lld
		-nostdlib
		-L/sysroot/usr/lib
	)

	if [[ ${runtime} == yes ]]; then
		compiler_rt=$(clang "--target=${target}" --rtlib=compiler-rt --print-libgcc-file-name)

		libraries+=(
			-lc
			"${compiler_rt}"
		)
	fi

	if [[ ${executable} == yes ]]; then
		arguments+=(
		-Wl,--dynamic-linker=/usr/lib/ld.so
		/sysroot/usr/lib/crt1.o
		/sysroot/usr/lib/crti.o
		)
		libraries+=(/sysroot/usr/lib/crtn.o)
	fi
fi

exec clang "${arguments[@]}" "$@" "${libraries[@]}"
